### PR TITLE
Always set ApprovalCount to 0 when RequireApproval is false

### LINKED ISSUE #419: Not requiring approvals does not imply approval count of 0?
Consider this either a question or a bug report 😄 

When setting
```
requireApproval: false
```
in `branch_protection.yaml`, one still gets the error
> PR Approvals below threshold 0 : 1 for branch main

if "Require a pull request before merging" is active and "Require approvals" is not active in a repository.

Question: Shouldn't `requireApproval: false` imply `approvalCount: 0`? And if not: Should this "surprising" (at least for me) behaviour be documented?

### PR DESCRIPTION
**Pull request by jamestran201**
Fixes https://github.com/ossf/allstar/issues/419

This PR explicitly sets the `ApprovalCount` to 0 when `RequireApproval` is `false` because not requiring approval implies that zero approval count is needed.

### CODE REVIEW

File: pkg/policies/branch/branch.go [hunk 1]
```diff
@@ -758,6 +759,11 @@ func mergeConfig(oc *OrgConfig, orc, rc *RepoConfig, repo string) *mergedConfig
 	if !oc.OptConfig.DisableRepoOverride {
 		mc = mergeInRepoConfig(mc, rc, repo)
 	}
+
+	if !mc.RequireApproval {
+		mc.ApprovalCount = 0
+	}
```
Comment (jamestran201) [inline pkg/policies/branch/branch.go:765]: Please let me know if this is not the right place to add the change, thanks!

**Review by jeffmendoza — APPROVED** [review]

**Comment by jeffmendoza** [comment]
Thanks!
